//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Dish
    {
        public int DishesId { get; set; }
        public string DishesName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual DishesCategory DishesCategory { get; set; }
        
        // not mapping property
        [NotMapped]
        public string DishesImg
        {
            get { return this.DishesId.ToString() + ".png"; }
        }
    }
}
