//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishesBook
    {
        public int BookId { get; set; }
        public string HotelName { get; set; }
        public Nullable<System.DateTime> ConsumeTime { get; set; }
        public Nullable<int> ConsumePersons { get; set; }
        public string RoomType { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> BookTime { get; set; }
        public Nullable<int> OrderStatus { get; set; }
    }
}
