//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContents { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
