//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public int PostId { get; set; }
        public string PostName { get; set; }
        public string PostType { get; set; }
        public string PostPlace { get; set; }
        public string PostDesc { get; set; }
        public string PostRequire { get; set; }
        public string Experience { get; set; }
        public string EduBackground { get; set; }
        public Nullable<int> RequireCount { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string Manager { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}
