//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public int SuggestionId { get; set; }
        public string CustomerName { get; set; }
        public string ConsumeDesc { get; set; }
        public string SuggestionDesc { get; set; }
        public Nullable<System.DateTime> SuggestionTime { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
