//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Models;
    using System.Configuration;
    
    public partial class RestaurantDBEntities : DbContext
    {
        public RestaurantDBEntities()
         //   : base("name=RestaurantDBEntities")
         :base(GetConnectionString())
        {
        }

        private static string GetConnectionString()
        {
            var connString = System.Configuration.ConfigurationManager.ConnectionStrings["RestaurantDBEntities"].ToString();
            return connString;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<DishesBook> DishesBooks { get; set; }
        public virtual DbSet<DishesCategory> DishesCategories { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsCategory> NewsCategories { get; set; }
        public virtual DbSet<Recruitment> Recruitments { get; set; }
        public virtual DbSet<Suggestion> Suggestions { get; set; }
        public virtual DbSet<SysAdmin> SysAdmins { get; set; }
    }
}
